source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

project 'QRCoderExample.xcodeproj'

target 'QRCoderOSXExample' do
    platform :osx, '10.9'
    pod 'QRCoder', '~> 1.1'
end

target 'QRCoderOSXTests' do
    platform :osx, '10.9'
    pod 'QRCoder', '~> 1.1'
end

target 'QRCoderiOSExample' do
    platform :ios, '8.0'
    pod 'QRCoder', '~> 1.1'
end

target 'QRCoderiOSTests' do
    platform :ios, '8.0'
    pod 'QRCoder', '~> 1.1'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|            
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
    
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end
